function Helper(){this.easyAjaxUpdateContent=function(type,blocks,data,action){for(var i=0;i<blocks.length;i++){var blockName=blocks[i][0];var selector=blocks[i][1];var html='';switch(type){case'custom':html=jQuery.trim(data.custom_content_data[blockName]);break;default:html=jQuery.trim(data.action_content_data[blockName]);}jQuery(selector)[action](html);}}
this.addHtmlWithJs=function($object,html,action){if(html=='null')return;if(html){$object[action](html);$(html).filter('script').each(function(i){var script=$(this).html();script=_helper.replaceAll(script,'window_addLoad','');script=_helper.replaceAll(script,'<!--','');script=_helper.replaceAll(script,'//-->','');var scriptTag=document.createElement("script");scriptTag.type="text/javascript";scriptTag.language='JavaScript1.2';scriptTag.text=script;$object[0].appendChild(scriptTag);eval(script);});}}
this.isCookiesEnabled=function(domain){var cookieName='isCookiesEnabled';var isEnabled=false;jQuery.cookie(cookieName,'1',{expires:1,path:'/',domain:domain,secure:false});isEnabled='1'==jQuery.cookie(cookieName);if(isEnabled){jQuery.removeCookie(cookieName,{path:'/',domain:domain,secure:false});}return isEnabled;}
this.IsValueInOptionList=function($element,value){var exists=false;$element.find('option').each(function(){if(this.value==value){exists=true;}});return exists;}
this.getQueryString=function(key){var query=window.location.search.substring(1);var vars=query.split("&");for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");if(pair[0]==key){return pair[1];}}}
this.Popup=function(url,title,width,height,windowFeatures){if(width==undefined){width=600;}if(height==undefined){height=375;}if(windowFeatures==undefined){windowFeatures='toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no,left=0,top=0';}var windowFeatures=windowFeatures+',width='+width+',height='+height;window.open(url,title,windowFeatures);return(true);}
this.getElementsByTagName=function(data,name){var returnValue='';if(data.getElementsByTagName(name)[0].childNodes[0]!=null){returnValue=data.getElementsByTagName(name)[0].childNodes[0].nodeValue;}return returnValue;}
this.getFileNameFromPath=function(path){var filename='';if(path.length>0){filename=path.replace(/^.*[\\\/]/,'');}return filename;}
this.replaceAll=function(s,oldValue,newValue){return s.replace(new RegExp(oldValue,'gi'),newValue);}
this.NaNToZero=function(n){if(isNaN(n)){return 0;}else{return n;}}
this.scrollToElm=function(elm,treshold){treshold=typeof treshold!=='undefined'?treshold:0;jQuery('html, body').animate({scrollTop:elm.offset().top-treshold},700);}}